// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dogeannkwxclyedwefgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvZ2Vhbm5rd3hjbHllZHdlZmdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMjgzNjMsImV4cCI6MjA2OTYwNDM2M30.Tl6YnaBRsXcXTfq3zczD5WH134HF_JLANmb5kXW9Tgs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});